In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option("display.max_columns", None)

df = pd.read_excel("C:/Users/ASUS/OneDrive/Desktop/RADHA/Semester/1st sem/Marketing/Survey_Data_Raw.xlsx")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 88
Columns: 20

,Timestamp,Education level,Age group,Gender,Occupation,Monthly household income (INR):,City category\n,Have you watched a movie in a cinema theatre in the past 12 months?,"Do you currently use any OTT/video streaming platforms (Netflix, Amazon Prime, Hotstar, etc.)?",Do you currently have any OTT subscription?,How many hours per week do you watch OTT content?,I prefer watching new movies at home rather than going to theatres,Watching in theatres feels like a special experience worth paying for.,OTT provides better convenience and variety than theatres.,I am willing to pay extra for early OTT release or premium experience.,Expensive tickets stop me from visiting theatres frequently.,"If a new blockbuster released today, which would you choose?","If OTT prices increased by 25%, would you continue your subscription?",How long should the gap be between theatre and OTT release?,What makes you decide between watching a movie in theatre vs OTT?
0,2025/11/08 11:28:34 am GMT+5:30,Graduate,15–24,Female,Student,NaN,Metro,Yes,yes,No,8–14 hours,4.0,4.0,4.0,4.0,4.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,No gap (same day release),NaN
1,2025/11/08 11:39:57 am GMT+5:30,Postgraduate or above,15–24,Female,Student,NaN,Small town / rural,Yes,yes,No,1–3 hours,3.0,5.0,3.0,4.0,5.0,Wait and watch on OTT (₹299/month),Probably no,No gap (same day release),NaN
2,2025/11/08 12:09:11 pm GMT+5:30,Graduate,15–24,Female,Salaried,"25,000-49,999",Metro,Yes,yes,Yes,1–3 hours,5.0,3.0,5.0,3.0,4.0,Wait and watch on OTT (₹299/month),Not sure,1 month,Comfort zone and time schedule
3,2025/11/08 12:10:18 pm GMT+5:30,Postgraduate or above,15–24,Male,Student,"<25,000",Tier 2,Yes,yes,Yes,1–3 hours,4.0,5.0,4.0,4.0,2.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,1 month,Theatre
4,2025/11/08 12:10:27 pm GMT+5:30,Graduate,15–24,Male,Student,>2 Lakh,Tier 2,Yes,yes,No,4–7 hours,3.0,4.0,1.0,1.0,3.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Definitely no,1 month,The movie theater screens are of different str...

In [38]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Timestamp,88,NaN,NaN,NaN,2025-11-08 20:42:59.340909568-05:30,2025-11-08 11:28:34-05:30,2025-11-08 12:41:58-05:30,2025-11-08 13:44:05-05:30,2025-11-08 19:33:05.750000128-05:30,2025-11-15 00:11:20-05:30,NaN
Education_Level,88,4,Postgraduate or above,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age_Group,88,5,15–24,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,88,3,Female,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Occupation,88,5,Student,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Income_Group,88,6,"<25,000",30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City_Category,88,4,Small town / rural,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cinema_Visit,88,3,Yes,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTT_User,88,4,Yes,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTT_Subscription,88,3,No,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTT_Hours,88,6,1–3 hours,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Home_Movie_Preference,85.0,NaN,NaN,NaN,3.329412,1.0,3.0,3.0,4.0,5.0,1.33976
Cinema_Experience,84.0,NaN,NaN,NaN,3.27381,1.0,3.0,3.0,4.0,5.0,1.13383
OTT_Convenience,84.0,NaN,NaN,NaN,3.392857,1.0,3.0,4.0,4.0,5.0,1.182379
Premium_OTT_WTP,84.0,NaN,NaN,NaN,2.416667,1.0,1.0,2.0,3.0,5.0,1.224335
Ticket_Price_Barrier,84.0,NaN,NaN,NaN,3.214286,1.0,2.0,3.0,5.0,5.0,1.465025
Blockbuster_Choice,88,4,"Watch in cinema (₹300 ticket, 1 month before OTT)",40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTT_Price_Response,88,6,Not sure,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Release_Gap,88,6,1 month,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Decision_Factor,88,60,,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OTT_Hours_Numeric,54.0,NaN,NaN,NaN,3.888889,2.0,2.0,2.0,5.5,15.0,3.25006
Choice_Simple,88,4,Cinema,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Response_Date,88,5,2025-11-08,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Response_Hour,88.0,NaN,NaN,NaN,13.409091,0.0,12.0,13.0,14.0,22.0,3.515602
OTT_Engagement_Score,54.0,NaN,NaN,NaN,3.888889,2.0,2.0,2.0,5.5,15.0,3.25006
Cinema_Experience_Score,84.0,NaN,NaN,NaN,3.27381,1.0,3.0,3.0,4.0,5.0,1.13383
Price_Sensitivity_Score,84.0,NaN,NaN,NaN,3.214286,1.0,2.0,3.0,5.0,5.0,1.465025

In [37]:
df.nunique()

Timestamp                  88
Education_Level             4
Age_Group                   5
Gender                      3
Occupation                  5
Income_Group                6
City_Category               4
Cinema_Visit                3
OTT_User                    4
OTT_Subscription            3
OTT_Hours                   6
Home_Movie_Preference       5
Cinema_Experience           5
OTT_Convenience             5
Premium_OTT_WTP             5
Ticket_Price_Barrier        5
Blockbuster_Choice          4
OTT_Price_Response          6
Release_Gap                 6
Decision_Factor            60
OTT_Hours_Numeric           4
Choice_Simple               4
Response_Date               5
Response_Hour              16
OTT_Engagement_Score        4
Cinema_Experience_Score     5
Price_Sensitivity_Score     5
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 20 columns):
 #   Column                                                                                          Non-Null Count  Dtype
---  ------                                                                                          --------------  -----
 0   Timestamp                                                                                       88 non-null     object
 1   Education level                                                                                 85 non-null     object
 2    Age group                                                                                      85 non-null     object
 3   Gender                                                                                          85 non-null     object
 4   Occupation                                                                                      85 non-null     object
 5    Monthly household income (INR):                                                                79 non-null     object
 6   City category
                                                                                  84 non-null     object
 7   Have you watched a movie in a cinema theatre in the past 12 months?                             85 non-null     object
 8   Do you currently use any OTT/video streaming platforms (Netflix, Amazon Prime, Hotstar, etc.)?  85 non-null     object
 9   Do you currently have any OTT subscription?                                                     85 non-null     object
 10  How many hours per week do you watch OTT content?                                               82 non-null     object
 11  I prefer watching new movies at home rather than going to theatres                              85 non-null     float64
 12  Watching in theatres feels like a special experience worth paying for.                          84 non-null     float64
 13  OTT provides better convenience and variety than theatres.                                      84 non-null     float64
 14   I am willing to pay extra for early OTT release or premium experience.                         84 non-null     float64
 15   Expensive tickets stop me from visiting theatres frequently.                                   84 non-null     float64
 16  If a new blockbuster released today, which would you choose?                                    81 non-null     object
 17  If OTT prices increased by 25%, would you continue your subscription?                           85 non-null     object
 18  How long should the gap be between theatre and OTT release?                                     85 non-null     object
 19  What makes you decide between watching a movie in theatre vs OTT?                               65 non-null     object
dtypes: float64(5), object(15)
memory usage: 13.9+ KB

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Timestamp,88,88,2025/11/08 11:28:34 am GMT+5:30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Education level,85,3,Postgraduate or above,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age group,85,4,15–24,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,85,2,Female,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Occupation,85,4,Student,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Monthly household income (INR):,79,5,"<25,000",30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City category\n,84,3,Small town / rural,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Have you watched a movie in a cinema theatre in the past 12 months?,85,2,Yes,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Do you currently use any OTT/video streaming platforms (Netflix, Amazon Prime, Hotstar, etc.)?",85,3,yes,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Do you currently have any OTT subscription?,85,2,No,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
How many hours per week do you watch OTT content?,82,5,1–3 hours,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I prefer watching new movies at home rather than going to theatres,85.0,NaN,NaN,NaN,3.329412,1.33976,1.0,3.0,3.0,4.0,5.0
Watching in theatres feels like a special experience worth paying for.,84.0,NaN,NaN,NaN,3.27381,1.13383,1.0,3.0,3.0,4.0,5.0
OTT provides better convenience and variety than theatres.,84.0,NaN,NaN,NaN,3.392857,1.182379,1.0,3.0,4.0,4.0,5.0
I am willing to pay extra for early OTT release or premium experience.,84.0,NaN,NaN,NaN,2.416667,1.224335,1.0,1.0,2.0,3.0,5.0
Expensive tickets stop me from visiting theatres frequently.,84.0,NaN,NaN,NaN,3.214286,1.465025,1.0,2.0,3.0,5.0,5.0
"If a new blockbuster released today, which would you choose?",81,3,"Watch in cinema (₹300 ticket, 1 month before OTT)",40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"If OTT prices increased by 25%, would you continue your subscription?",85,5,Not sure,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
How long should the gap be between theatre and OTT release?,85,5,1 month,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
What makes you decide between watching a movie in theatre vs OTT?,65,59,Ott,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns = (
    df.columns
    .str.strip()
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
)

In [7]:
print(df.columns.tolist())

['Timestamp', 'Education level', 'Age group', 'Gender', 'Occupation', 'Monthly household income (INR):', 'City category', 'Have you watched a movie in a cinema theatre in the past 12 months?', 'Do you currently use any OTT/video streaming platforms (Netflix, Amazon Prime, Hotstar, etc.)?', 'Do you currently have any OTT subscription?', 'How many hours per week do you watch OTT content?', 'I prefer watching new movies at home rather than going to theatres', 'Watching in theatres feels like a special experience worth paying for.', 'OTT provides better convenience and variety than theatres.', 'I am willing to pay extra for early OTT release or premium experience.', 'Expensive tickets stop me from visiting theatres frequently.', 'If a new blockbuster released today, which would you choose?', 'If OTT prices increased by 25%, would you continue your subscription?', 'How long should the gap be between theatre and OTT release?', 'What makes you decide between watching a movie in theatre vs OTT?']

In [8]:
column_mapping = {
    "Timestamp": "Timestamp",
    "Education level": "Education_Level",
    "Age group": "Age_Group",
    "Gender": "Gender",
    "Occupation": "Occupation",
    "Monthly household income (INR):": "Income_Group",
    "City category": "City_Category",
    "Have you watched a movie in a cinema theatre in the past 12 months?": "Cinema_Visit",
    "Do you currently use any OTT/video streaming platforms (Netflix, Amazon Prime, Hotstar, etc.)?": "OTT_User",
    "Do you currently have any OTT subscription?": "OTT_Subscription",
    "How many hours per week do you watch OTT content?": "OTT_Hours",
    "I prefer watching new movies at home rather than going to theatres": "Home_Movie_Preference",
    "Watching in theatres feels like a special experience worth paying for.": "Cinema_Experience",
    "OTT provides better convenience and variety than theatres.": "OTT_Convenience",
    "I am willing to pay extra for early OTT release or premium experience.": "Premium_OTT_WTP",
    "Expensive tickets stop me from visiting theatres frequently.": "Ticket_Price_Barrier",
    "If a new blockbuster released today, which would you choose?": "Blockbuster_Choice",
    "If OTT prices increased by 25%, would you continue your subscription?": "OTT_Price_Response",
    "How long should the gap be between theatre and OTT release?": "Release_Gap",
    "What makes you decide between watching a movie in theatre vs OTT?": "Decision_Factor"
}

df = df.rename(columns=column_mapping)

df.head()

,Timestamp,Education_Level,Age_Group,Gender,Occupation,Income_Group,City_Category,Cinema_Visit,OTT_User,OTT_Subscription,OTT_Hours,Home_Movie_Preference,Cinema_Experience,OTT_Convenience,Premium_OTT_WTP,Ticket_Price_Barrier,Blockbuster_Choice,OTT_Price_Response,Release_Gap,Decision_Factor
0,2025/11/08 11:28:34 am GMT+5:30,Graduate,15–24,Female,Student,NaN,Metro,Yes,yes,No,8–14 hours,4.0,4.0,4.0,4.0,4.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,No gap (same day release),NaN
1,2025/11/08 11:39:57 am GMT+5:30,Postgraduate or above,15–24,Female,Student,NaN,Small town / rural,Yes,yes,No,1–3 hours,3.0,5.0,3.0,4.0,5.0,Wait and watch on OTT (₹299/month),Probably no,No gap (same day release),NaN
2,2025/11/08 12:09:11 pm GMT+5:30,Graduate,15–24,Female,Salaried,"25,000-49,999",Metro,Yes,yes,Yes,1–3 hours,5.0,3.0,5.0,3.0,4.0,Wait and watch on OTT (₹299/month),Not sure,1 month,Comfort zone and time schedule
3,2025/11/08 12:10:18 pm GMT+5:30,Postgraduate or above,15–24,Male,Student,"<25,000",Tier 2,Yes,yes,Yes,1–3 hours,4.0,5.0,4.0,4.0,2.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,1 month,Theatre
4,2025/11/08 12:10:27 pm GMT+5:30,Graduate,15–24,Male,Student,>2 Lakh,Tier 2,Yes,yes,No,4–7 hours,3.0,4.0,1.0,1.0,3.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Definitely no,1 month,The movie theater screens are of different str...

Check missing values

In [9]:
missing = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (df.isna().mean() * 100).round(2)
})

missing = missing[missing["Missing_Count"] > 0]

missing.sort_values("Missing_Count", ascending=False)

                       Missing_Count  Missing_Percentage
Decision_Factor                   23               26.14
Income_Group                       9               10.23
Blockbuster_Choice                 7                7.95
OTT_Hours                          6                6.82
Premium_OTT_WTP                    4                4.55
City_Category                      4                4.55
Cinema_Experience                  4                4.55
OTT_Convenience                    4                4.55
Ticket_Price_Barrier               4                4.55
Education_Level                    3                3.41
Age_Group                          3                3.41
Gender                             3                3.41
Home_Movie_Preference              3                3.41
OTT_User                           3                3.41
Cinema_Visit                       3                3.41
Occupation                         3                3.41
OTT_Subscription                   3                3.41
OTT_Price_Response                 3                3.41
Release_Gap                        3                3.41

Handle categorical missing values

In [10]:
categorical_cols = [
    "Education_Level",
    "Age_Group",
    "Gender",
    "Occupation",
    "Income_Group",
    "City_Category",
    "Cinema_Visit",
    "OTT_User",
    "OTT_Subscription",
    "OTT_Hours",
    "Blockbuster_Choice",
    "OTT_Price_Response",
    "Release_Gap"
]

for col in categorical_cols:
    df[col] = df[col].fillna("Not Specified")

Handle the open-ended question

In [11]:
df["Decision_Factor"] = df["Decision_Factor"].fillna("")   #Decision_Factor

Standardize Yes/No variables

In [12]:
yes_no_cols = [
    "Cinema_Visit",
    "OTT_User",
    "OTT_Subscription"
]

for col in yes_no_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace({
            "yes": "Yes",
            "no": "No"
        })
    )

In [13]:
for col in yes_no_cols:
    print("\n", col)
    print(df[col].value_counts())

 Cinema_Visit
Cinema_Visit
Yes              66
No               19
not specified     3
Name: count, dtype: int64

 OTT_User
OTT_User
Yes              61
No               23
not specified     3
yes;no            1
Name: count, dtype: int64

 OTT_Subscription
OTT_Subscription
No               46
Yes              39
not specified     3
Name: count, dtype: int64

Clean OTT Hours

In [ ]:
ott_hours_mapping = {
    "<1 hour": 0.5,
    "1–3 hours": 2,
    "4–7 hours": 5.5,
    "8–14 hours": 11,
    "15+ hours": 15
}

df["OTT_Hours_Numeric"] = df["OTT_Hours"].map(ott_hours_mapping)  # for categorical analysis

Check Likert variables

In [15]:
likert_cols = [
    "Home_Movie_Preference",
    "Cinema_Experience",
    "OTT_Convenience",
    "Premium_OTT_WTP",
    "Ticket_Price_Barrier"
]

In [16]:
for col in likert_cols:
    print("\n", col)
    print(df[col].value_counts().sort_index())

 Home_Movie_Preference
Home_Movie_Preference
1.0    13
2.0     6
3.0    27
4.0    18
5.0    21
Name: count, dtype: int64

 Cinema_Experience
Cinema_Experience
1.0     9
2.0     6
3.0    34
4.0    23
5.0    12
Name: count, dtype: int64

 OTT_Convenience
OTT_Convenience
1.0    10
2.0     4
3.0    27
4.0    29
5.0    14
Name: count, dtype: int64

 Premium_OTT_WTP
Premium_OTT_WTP
1.0    24
2.0    23
3.0    21
4.0    10
5.0     6
Name: count, dtype: int64

 Ticket_Price_Barrier
Ticket_Price_Barrier
1.0    15
2.0    14
3.0    16
4.0    16
5.0    23
Name: count, dtype: int64

In [17]:
for col in likert_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [18]:
df[likert_cols].describe().T

                       count      mean       std  min  25%  50%  75%  max
Home_Movie_Preference   85.0  3.329412  1.339760  1.0  3.0  3.0  4.0  5.0
Cinema_Experience       84.0  3.273810  1.133830  1.0  3.0  3.0  4.0  5.0
OTT_Convenience         84.0  3.392857  1.182379  1.0  3.0  4.0  4.0  5.0
Premium_OTT_WTP         84.0  2.416667  1.224335  1.0  1.0  2.0  3.0  5.0
Ticket_Price_Barrier    84.0  3.214286  1.465025  1.0  2.0  3.0  5.0  5.0

Validate Likert values

In [19]:
for col in likert_cols:
    invalid = df.loc[
        ~df[col].isin([1, 2, 3, 4, 5]) & df[col].notna(),
        col
    ]
    
    print(col, "Invalid values:", invalid.tolist())

Home_Movie_Preference Invalid values: []
Cinema_Experience Invalid values: []
OTT_Convenience Invalid values: []
Premium_OTT_WTP Invalid values: []
Ticket_Price_Barrier Invalid values: []

Clean Blockbuster Choice

In [20]:
df["Blockbuster_Choice"].value_counts(dropna=False)

Blockbuster_Choice
Watch in cinema (₹300 ticket, 1 month before OTT)      40
Wait and watch on OTT (₹299/month)                     34
Not Specified                                           7
Pay ₹499 to watch on OTT same day as theatre (PVOD)     7
Name: count, dtype: int64

In [21]:
def simplify_choice(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower()
    
    if "cinema" in x:
        return "Cinema"
    elif "wait" in x and "ott" in x:
        return "OTT"
    elif "499" in x or "same day" in x:
        return "PVOD"
    else:
        return "Other"

df["Choice_Simple"] = df["Blockbuster_Choice"].apply(simplify_choice)

In [22]:
df["Choice_Simple"].value_counts(dropna=False)

Choice_Simple
Cinema    40
OTT       34
Other      7
PVOD       7
Name: count, dtype: int64

Create a clean demographic table

In [23]:
demographic_cols = [
    "Education_Level",
    "Age_Group",
    "Gender",
    "Occupation",
    "Income_Group",
    "City_Category"
]

for col in demographic_cols:
    print("\n==========", col, "==========")
    print(df[col].value_counts(dropna=False))

========== Education_Level ==========
Education_Level
Postgraduate or above    39
Graduate                 38
High school               8
Not Specified             3
Name: count, dtype: int64

========== Age_Group ==========
Age_Group
15–24            63
25–34            19
Not Specified     3
45–54             2
35–44             1
Name: count, dtype: int64

========== Gender ==========
Gender
Female           47
Male             38
Not Specified     3
Name: count, dtype: int64

========== Occupation ==========
Occupation
Student          59
Salaried         17
Self-employed     6
Not Specified     3
Other             3
Name: count, dtype: int64

========== Income_Group ==========
Income_Group
<25,000          30
25,000-49,999    14
50,000–99,999    14
1–2 Lakh         11
>2 Lakh          10
Not Specified     9
Name: count, dtype: int64

========== City_Category ==========
City_Category
Small town / rural    44
Tier 2                24
Metro                 16
Not Specified          4
Name: count, dtype: int64

In [24]:
df["Gender"] = (
    df["Gender"]
    .str.strip()
    .str.title()
)

df["Occupation"] = (
    df["Occupation"]
    .str.strip()
    .str.title()
)

Check duplicate responses

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Timestamp, Education_Level, Age_Group, Gender, Occupation, Income_Group, City_Category, Cinema_Visit, OTT_User, OTT_Subscription, OTT_Hours, Home_Movie_Preference, Cinema_Experience, OTT_Convenience, Premium_OTT_WTP, Ticket_Price_Barrier, Blockbuster_Choice, OTT_Price_Response, Release_Gap, Decision_Factor, OTT_Hours_Numeric, Choice_Simple]
Index: []

Timestamp cleaning

In [28]:
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

In [29]:
df["Response_Date"] = df["Timestamp"].dt.date
df["Response_Hour"] = df["Timestamp"].dt.hour

Creating the first derived variables

In [30]:
df["OTT_Engagement_Score"] = (
    df["OTT_Hours_Numeric"]
)

In [31]:
df["Cinema_Experience_Score"] = df["Cinema_Experience"]

In [32]:
df["Price_Sensitivity_Score"] = df["Ticket_Price_Barrier"]

Data-Quality Check

In [33]:
print("Dataset shape:", df.shape)

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nMissing values:")
print(df.isna().sum())

print("\nData types:")
print(df.dtypes)

Dataset shape: (88, 27)

Duplicate rows:
0

Missing values:
Timestamp                   0
Education_Level             0
Age_Group                   0
Gender                      0
Occupation                  0
Income_Group                0
City_Category               0
Cinema_Visit                0
OTT_User                    0
OTT_Subscription            0
OTT_Hours                   0
Home_Movie_Preference       3
Cinema_Experience           4
OTT_Convenience             4
Premium_OTT_WTP             4
Ticket_Price_Barrier        4
Blockbuster_Choice          0
OTT_Price_Response          0
Release_Gap                 0
Decision_Factor             0
OTT_Hours_Numeric          34
Choice_Simple               0
Response_Date               0
Response_Hour               0
OTT_Engagement_Score       34
Cinema_Experience_Score     4
Price_Sensitivity_Score     4
dtype: int64

Data types:
Timestamp                  datetime64[ns, UTC-05:30]
Education_Level                               object
Age_Group                                     object
Gender                                        object
Occupation                                    object
Income_Group                                  object
City_Category                                 object
Cinema_Visit                                  object
OTT_User                                      object
OTT_Subscription                              object
OTT_Hours                                     object
Home_Movie_Preference                        float64
Cinema_Experience                            float64
OTT_Convenience                              float64
Premium_OTT_WTP                              float64
Ticket_Price_Barrier                         float64
Blockbuster_Choice                            object
OTT_Price_Response                            object
Release_Gap                                   object
Decision_Factor                               object
OTT_Hours_Numeric                            float64
Choice_Simple                                 object
Response_Date                                 object
Response_Hour                                  int32
OTT_Engagement_Score                         float64
Cinema_Experience_Score                      float64
Price_Sensitivity_Score                      float64
dtype: object

In [34]:
df.head()

,Timestamp,Education_Level,Age_Group,Gender,Occupation,Income_Group,City_Category,Cinema_Visit,OTT_User,OTT_Subscription,OTT_Hours,Home_Movie_Preference,Cinema_Experience,OTT_Convenience,Premium_OTT_WTP,Ticket_Price_Barrier,Blockbuster_Choice,OTT_Price_Response,Release_Gap,Decision_Factor,OTT_Hours_Numeric,Choice_Simple,Response_Date,Response_Hour,OTT_Engagement_Score,Cinema_Experience_Score,Price_Sensitivity_Score
0,2025-11-08 11:28:34-05:30,Graduate,15–24,Female,Student,Not Specified,Metro,Yes,Yes,No,8–14 hours,4.0,4.0,4.0,4.0,4.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,No gap (same day release),,11.0,Cinema,2025-11-08,11,11.0,4.0,4.0
1,2025-11-08 11:39:57-05:30,Postgraduate or above,15–24,Female,Student,Not Specified,Small town / rural,Yes,Yes,No,1–3 hours,3.0,5.0,3.0,4.0,5.0,Wait and watch on OTT (₹299/month),Probably no,No gap (same day release),,2.0,OTT,2025-11-08,11,2.0,5.0,5.0
2,2025-11-08 12:09:11-05:30,Graduate,15–24,Female,Salaried,"25,000-49,999",Metro,Yes,Yes,Yes,1–3 hours,5.0,3.0,5.0,3.0,4.0,Wait and watch on OTT (₹299/month),Not sure,1 month,Comfort zone and time schedule,2.0,OTT,2025-11-08,12,2.0,3.0,4.0
3,2025-11-08 12:10:18-05:30,Postgraduate or above,15–24,Male,Student,"<25,000",Tier 2,Yes,Yes,Yes,1–3 hours,4.0,5.0,4.0,4.0,2.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Not sure,1 month,Theatre,2.0,Cinema,2025-11-08,12,2.0,5.0,2.0
4,2025-11-08 12:10:27-05:30,Graduate,15–24,Male,Student,>2 Lakh,Tier 2,Yes,Yes,No,4–7 hours,3.0,4.0,1.0,1.0,3.0,"Watch in cinema (₹300 ticket, 1 month before OTT)",Definitely no,1 month,The movie theater screens are of different str...,5.5,Cinema,2025-11-08,12,5.5,4.0,3.0

Save the cleaned dataset

In [35]:
df.to_csv(
    "Survey_Data_Cleaned.csv",
    index=False
)